# Generated by Django 4.0.3 on 2022-04-14 09:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('space marine', 'space marine'), ('astra militarum', 'astra militarum'), ('chaos space marines', 'chaos space marines'), ('necrons', 'necrons'), ('orks', 'orks'), ('aeldar', 'aeldar')], max_length=19)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoughtItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('type', models.CharField(choices=[('space marine', 'space marine'), ('astra militarum', 'astra militarum'), ('chaos space marines', 'chaos space marines'), ('necrons', 'necrons'), ('orks', 'orks'), ('aeldar', 'aeldar')], max_length=19)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('article', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('title_image', models.ImageField(upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
