# Generated by Django 4.0.3 on 2022-04-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='title_image',
            field=models.URLField(),
        ),
    ]
